# Generated by Django 6.0.4 on 2026-04-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_email', models.CharField(blank=True, max_length=200, null=True)),
                ('notification_type', models.CharField(choices=[('attendance', 'Attendance Alert'), ('grade', 'Grade Report'), ('announcement', 'Announcement'), ('reminder', 'Reminder')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
