apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: edutrack
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,.elb.amazonaws.com"
  DATABASE_HOST: "edutrack-db.c7aoaiukucxw.eu-north-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_USER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: edutrack
type: Opaque
stringData:
  DATABASE_PASSWORD: "EduTrack2026!"
  SECRET_KEY: "your-django-secret-key-change-this-in-production"
